### ISSUE TITLE
Chat text is invisible until I click edit.

### ISSUE THREAD

**Issue by khdc** [wieslawsoltes/ChatGPT#44] opened 2023-04-05 15:06 UTC
I'm running on Windows 11. All chat text is invisible. It will only display after clicking the edit button for each entry. After exiting editing, the text disappears.

![image](https://user-images.githubusercontent.com/18103151/230122954-9b8bf29c-32f7-4c5b-ad59-3a2128ae1933.png)

**Comment by wieslawsoltes** [comment] 2023-04-05 16:24
Known issue caused by linker trimming. The message controls got trimmed during publishing executables. Will fix ASAP.

**Comment by wieslawsoltes** [comment] 2023-04-05 19:21
Hopefully will be fixed in next preview

**Comment by wieslawsoltes** [comment] 2023-04-05 19:57
Fixed in preview.11 https://github.com/wieslawsoltes/ChatGPT/releases/tag/1.0.0-preview.11

**Closed by wieslawsoltes** 2023-04-05 19:57 UTC
Labels: bug

**Comment by giuliohome** [comment] 2024-06-01 08:30
I'm not sure I understand.
Yesterday I cloned the repo built and moved the apk to my phone and this bug is still present.
Is the preview tag not yet merged into the main trunk even though the issue has been closed a month ago? 
Thank you.
